service:
  name: HarvestLogger

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  entrypoint:
    handler: handler.entrypoint
    events:
      - alexaSkill
